/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import { Context as ContextModule } from "./api/context"


declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  AuthPayload: { // root type
    token?: string | null; // String
    user?: NexusGenRootTypes['User'] | null; // User
  }
  Block: { // root type
    content?: string | null; // String
    id?: number | null; // Int
    type?: string | null; // String
  }
  Mutation: {};
  Page: { // root type
    cover?: string | null; // String
    emoji?: string | null; // String
    id?: number | null; // Int
    title?: string | null; // String
  }
  Query: {};
  User: { // root type
    confirmed?: string | null; // String
    email?: string | null; // String
    id?: number | null; // Int
    name?: string | null; // String
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  AuthPayload: { // field return type
    token: string | null; // String
    user: NexusGenRootTypes['User'] | null; // User
  }
  Block: { // field return type
    content: string | null; // String
    id: number | null; // Int
    type: string | null; // String
  }
  Mutation: { // field return type
    createBlock: NexusGenRootTypes['Block'] | null; // Block
    createPage: NexusGenRootTypes['Page'] | null; // Page
    deleteBlock: NexusGenRootTypes['Block'] | null; // Block
    deletePage: NexusGenRootTypes['Page'] | null; // Page
    login: NexusGenRootTypes['AuthPayload'] | null; // AuthPayload
    register: NexusGenRootTypes['AuthPayload'] | null; // AuthPayload
    updateBlock: NexusGenRootTypes['Block'] | null; // Block
    updatePage: NexusGenRootTypes['Page'] | null; // Page
  }
  Page: { // field return type
    cover: string | null; // String
    emoji: string | null; // String
    id: number | null; // Int
    title: string | null; // String
  }
  Query: { // field return type
    block: NexusGenRootTypes['Block'] | null; // Block
    blocks: Array<NexusGenRootTypes['Block'] | null> | null; // [Block]
    confirmedUsers: Array<NexusGenRootTypes['User'] | null> | null; // [User]
    me: NexusGenRootTypes['User'] | null; // User
    page: NexusGenRootTypes['Page'] | null; // Page
    pages: Array<NexusGenRootTypes['Page'] | null> | null; // [Page]
    user: NexusGenRootTypes['User'] | null; // User
    viewer: NexusGenRootTypes['User'] | null; // User
  }
  User: { // field return type
    confirmed: string | null; // String
    email: string | null; // String
    id: number | null; // Int
    name: string | null; // String
  }
}

export interface NexusGenFieldTypeNames {
  AuthPayload: { // field return type name
    token: 'String'
    user: 'User'
  }
  Block: { // field return type name
    content: 'String'
    id: 'Int'
    type: 'String'
  }
  Mutation: { // field return type name
    createBlock: 'Block'
    createPage: 'Page'
    deleteBlock: 'Block'
    deletePage: 'Page'
    login: 'AuthPayload'
    register: 'AuthPayload'
    updateBlock: 'Block'
    updatePage: 'Page'
  }
  Page: { // field return type name
    cover: 'String'
    emoji: 'String'
    id: 'Int'
    title: 'String'
  }
  Query: { // field return type name
    block: 'Block'
    blocks: 'Block'
    confirmedUsers: 'User'
    me: 'User'
    page: 'Page'
    pages: 'Page'
    user: 'User'
    viewer: 'User'
  }
  User: { // field return type name
    confirmed: 'String'
    email: 'String'
    id: 'Int'
    name: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createBlock: { // args
      content?: string | null; // String
      pageId?: number | null; // Int
      type?: string | null; // String
    }
    createPage: { // args
      cover?: string | null; // String
      emoji?: string | null; // String
      title: string; // String!
    }
    deleteBlock: { // args
      blockId?: number | null; // Int
    }
    deletePage: { // args
      pageId?: number | null; // Int
    }
    login: { // args
      email: string; // String!
      password: string; // String!
    }
    register: { // args
      email: string; // String!
      name: string; // String!
      password: string; // String!
    }
    updateBlock: { // args
      content?: string | null; // String
      pageId?: number | null; // Int
      type?: string | null; // String
    }
    updatePage: { // args
      cover?: string | null; // String
      emoji?: string | null; // String
      title?: string | null; // String
      userId?: number | null; // Int
    }
  }
  Query: {
    block: { // args
      id?: number | null; // Int
    }
    blocks: { // args
      pageId?: number | null; // Int
    }
    page: { // args
      id?: number | null; // Int
    }
    pages: { // args
      userId?: number | null; // Int
    }
    user: { // args
      id?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: ContextModule;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}